# Домашнее задание

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [21]:
import numpy as np

In [22]:
n = 20
a = np.flip(np.arange(0, n))
a

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

## Задание 2 
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали

In [23]:
n = 5
matrix = np.flip(np.diag(np.arange(0, n+1), k=0))
sample = []
i = 0
for sum_diag in matrix:
  sample.append(sum_diag[i])
  i += 1
print(matrix)
print('Сумма значений на диагонали', sum(sample))

[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
Сумма значений на диагонали 15


## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3 

In [24]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [25]:
from numpy import linalg

In [26]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [27]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True